warning_threshold: 10

force_cast:
  severity: warning

force_try:
  severity: warning

empty_count:
  severity: warning

file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 40
  error: 100

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_function_declarations: true

identifier_name:
  min_length:
    error: 0
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - colon
  - comma
  - closing_brace
  - closure_spacing
  - empty_count
  - closure_end_indentation
  - contains_over_first_not_nil
  - explicit_init
  - multiline_parameters
  - object_literal
  - overridden_super_call
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - Pods
  - Client
  - ClientTests
  - Interface
  - InterfaceTests
  - The-NorrisTests
  
